import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { HealthProfile } from "@/lib/medical-calculators";
import { AnomalyPoint, DriftResult } from "@/lib/advanced-analytics";

interface AgentResult {
  agent: string;
  output: any;
  reasoning: string;
}

interface ReportData {
  userName: string;
  profile: HealthProfile;
  agentResults: AgentResult[];
  anomalies: AnomalyPoint[];
  driftResults: DriftResult[];
  riskScores?: {
    framingham: { riskPercentage: number; riskCategory: string };
    findrisc: { riskPercentage: number; riskCategory: string };
  };
  simulations?: Array<{
    name: string;
    description: string;
    projectedImprovement?: string;
    projectedHealthScore?: number;
  }>;
  generatedAt: Date;
}

export const generateProfessionalPdf = (data: ReportData, filename: string = "FutureMe_AI_Health_Intelligence.pdf") => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // --- Header ---
  const addHeader = (pageNum: number) => {
    // Dark background banner
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, pageWidth, 40, "F");
    
    // Stylized logo icon (Simplified to avoid corruption)
    const iconX = margin;
    const iconY = 15;
    
    // Icon shape (Neon teal/emerald)
    doc.setDrawColor(45, 212, 191); // teal-400
    doc.setLineWidth(1.5);
    doc.rect(iconX, iconY + 5, 8, 8, "S");
    doc.setFillColor(45, 212, 191);
    doc.circle(iconX + 4, iconY + 9, 1.5, "F"); // Center dot
    
    // FutureMe Text Branding
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    
    // "FUTURE" in White
    doc.setTextColor(255, 255, 255);
    doc.text("FUTURE", iconX + 12, 26);
    
    // "ME" in Teal
    const futureWidth = doc.getTextWidth("FUTURE");
    doc.setTextColor(45, 212, 191); // teal-400
    doc.text("ME", iconX + 12 + futureWidth + 1, 26);
    
    // Report Subtitle
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("HEALTH INTELLIGENCE REPORT", pageWidth - margin, 20, { align: "right" });
    doc.setTextColor(200, 200, 200);
    doc.text(format(data.generatedAt, "PPP"), pageWidth - margin, 28, { align: "right" });
  };

  // --- Footer ---
  const addFooter = (pageNum: number) => {
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Disclaimer: This report is generated by AI for educational purposes only. Not a medical device or diagnosis.",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  };

  addHeader(1);
  let yPos = 55;

  // --- Section 1: User Profile ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("1. Health Foundation Profile", margin, yPos);
  yPos += 10;

  const profileData = [
    ["Metric", "Value"],
    ["Patient Name", data.userName],
    ["Age", `${data.profile.age} years`],
    ["Sex", data.profile.sex.charAt(0).toUpperCase() + data.profile.sex.slice(1)],
    ["Height/Weight", `${data.profile.heightCm}cm / ${data.profile.weightKg}kg`],
    ["Calculated BMI", (data.profile.weightKg / Math.pow(data.profile.heightCm / 100, 2)).toFixed(1)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [profileData[0]],
    body: profileData.slice(1),
    margin: { left: margin },
    theme: "striped",
    headStyles: { fillColor: [45, 212, 191], textColor: [255, 255, 255] }, // teal-400
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // --- Section 2: AI Agent Analysis ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("2. Multi-Agent AI Intelligence", margin, yPos);
  yPos += 10;

  data.agentResults.forEach((result, idx) => {
    if (yPos > 240) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      addHeader(doc.getNumberOfPages());
      yPos = 55;
    }

    const agentLabels: Record<string, string> = {
      planner: "Planner Agent",
      risk_analysis: "Risk Analysis Agent",
      recommendation: "Recommendation Agent",
      simulation: "Simulation Agent",
    };

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(45, 212, 191);
    doc.text(agentLabels[result.agent] || result.agent, margin, yPos);
    yPos += 6;

    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    const splitReasoning = doc.splitTextToSize(`Reasoning: ${result.reasoning}`, pageWidth - margin * 2);
    doc.text(splitReasoning, margin, yPos);
    yPos += splitReasoning.length * 4 + 4;

    const output = result.output;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);

    if (output.overallAssessment || output.analysis) {
      const mainText = output.overallAssessment || output.analysis;
      const splitText = doc.splitTextToSize(mainText, pageWidth - margin * 2);
      doc.text(splitText, margin, yPos);
      yPos += splitText.length * 5 + 4;
    }

    if (output.riskInsights && output.riskInsights.length > 0) {
      if (yPos > 260) {
        addFooter(doc.getNumberOfPages());
        doc.addPage();
        addHeader(doc.getNumberOfPages());
        yPos = 55;
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text("Risk Indicators:", margin, yPos);
      yPos += 5;
      doc.setFont("helvetica", "normal");
      output.riskInsights.forEach((ri: any) => {
        if (yPos > 265) {
          addFooter(doc.getNumberOfPages());
          doc.addPage();
          addHeader(doc.getNumberOfPages());
          yPos = 55;
        }
        // FIX: wrap long risk text and measure actual height
        const riText = `- ${ri.risk}: ${ri.explanation} (${ri.level.toUpperCase()})`;
        const splitRi = doc.splitTextToSize(riText, pageWidth - margin * 2 - 5);
        doc.text(splitRi, margin + 5, yPos);
        yPos += splitRi.length * 5 + 2; // FIX: advance by actual line count, not flat +5
      });
      yPos += 2;
    }

    if (output.recommendations && output.recommendations.length > 0) {
      if (yPos > 260) {
        addFooter(doc.getNumberOfPages());
        doc.addPage();
        addHeader(doc.getNumberOfPages());
        yPos = 55;
      }
      doc.setFont("helvetica", "bold");
      doc.text("Key Recommendations:", margin, yPos);
      yPos += 6;
      doc.setFont("helvetica", "normal");
      output.recommendations.forEach((rec: any) => {
        if (yPos > 255) {
          addFooter(doc.getNumberOfPages());
          doc.addPage();
          addHeader(doc.getNumberOfPages());
          yPos = 55;
        }
        // FIX: pre-split text and measure actual height before writing
        const recText = `\u2022 [${rec.priority?.toUpperCase() || "MED"}] ${rec.title}: ${rec.description}`;
        const splitRec = doc.splitTextToSize(recText, pageWidth - margin * 2 - 5);
        doc.text(splitRec, margin + 5, yPos);
        yPos += splitRec.length * 5 + 4; // FIX: advance by actual wrapped line count
      });
      yPos += 4;
    }

    yPos += 5;
  });

  // --- Section 3: Anomalies & Behavioral Shifts ---
  if (data.anomalies.length > 0 || data.driftResults.length > 0) {
    if (yPos > 220) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      addHeader(doc.getNumberOfPages());
      yPos = 55;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("3. Behavioral Patterns & Anomalies", margin, yPos);
    yPos += 10;

    if (data.anomalies.length > 0) {
      doc.setFontSize(12);
      doc.text("Detected Anomalies", margin, yPos);
      yPos += 5;
      
      const anomalyRows = data.anomalies.map(a => [
        a.date,
        a.metric.replace(/_/g, " "),
        a.direction,
        a.severity
      ]);

      autoTable(doc, {
        startY: yPos,
        head: [["Date", "Metric", "Direction", "Severity"]],
        body: anomalyRows,
        margin: { left: margin },
        styles: { fontSize: 9 },
        headStyles: { fillColor: [239, 68, 68] } // red-500
      });
      yPos = (doc as any).lastAutoTable.finalY + 15;
    }
  }

  // --- Section 4: Medical Risk Predictions ---
  if (data.riskScores) {
    if (yPos > 240) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      addHeader(doc.getNumberOfPages());
      yPos = 55;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("4. Medical Risk Predictions", margin, yPos);
    yPos += 10;

    const riskData = [
      ["Medical Assessment", "Risk Level", "Category"],
      ["CVD Risk (Framingham)", `${data.riskScores.framingham.riskPercentage}%`, data.riskScores.framingham.riskCategory],
      ["Diabetes Risk (FINDRISC)", `${data.riskScores.findrisc.riskPercentage}%`, data.riskScores.findrisc.riskCategory],
    ];

    autoTable(doc, {
      startY: yPos,
      head: [riskData[0]],
      body: riskData.slice(1),
      margin: { left: margin },
      theme: "grid",
      headStyles: { fillColor: [71, 85, 105] },
    });
    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  // --- Section 5: Projected Future Simulations ---
  if (data.simulations && data.simulations.length > 0) {
    if (yPos > 240) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      addHeader(doc.getNumberOfPages());
      yPos = 55;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text("5. Projected Health Simulations", margin, yPos);
    yPos += 10;

    const simRows = data.simulations.map(s => [
      s.name,
      s.description,
      s.projectedHealthScore ? `${s.projectedHealthScore}/100` : (s.projectedImprovement || "N/A")
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Scenario", "Description", "Projected Improvement"]],
      body: simRows,
      margin: { left: margin },
      styles: { fontSize: 9 },
      headStyles: { fillColor: [5, 150, 105] } // emerald-600
    });
    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  addFooter(doc.getNumberOfPages());
  
  try {
    const blob = doc.output("blob");
    console.log(`Blob Generated: ${blob.size} bytes, type: ${blob.type}`);
    
    // Quick header check
    const reader = new FileReader();
    reader.onload = () => {
      const head = new TextDecoder().decode(new Uint8Array(reader.result as ArrayBuffer));
      console.log(`PDF Header: ${head}`);
    };
    reader.readAsArrayBuffer(blob.slice(0, 5));

    console.log(`Attempting to open PDF in new window for: ${filename}`);
    // dataurlnewwindow is very reliable for "readability" as it uses the browser's native PDF viewer
    doc.output("dataurlnewwindow", { filename });
    
    // Fallback: also trigger a download for persistence
    setTimeout(() => {
      console.log(`Triggering secondary download for: ${filename}`);
      doc.save(filename);
    }, 500);
    
  } catch (error) {
    console.error("PDF Display/Save failed:", error);
    doc.save(filename); // Final attempt
  }
};